server-name SmartDNS
resolv-hostname no
bind [::]:53
bind-tcp [::]:53
tcp-idle-time 30
cache-size 4194304
cache-persist no
cache-mem-size 134217728
serve-expired yes
serve-expired-ttl 259200
serve-expired-reply-ttl 3
serve-expired-prefetch-time 86400
prefetch-domain yes
speed-check-mode none
dualstack-ip-selection no
rr-ttl 0
rr-ttl-min 0
rr-ttl-max 86400
rr-ttl-reply-max 86400
response-mode fastest-response
log-console yes
log-level fatal
log-file /dev/null
log-num 0
audit-console yes
audit-enable yes
audit-syslog no
audit-file /dev/null
audit-num 0
ca-file /etc/ssl/certs/ca-certificates.crt
ca-path /etc/ssl/certs

server 119.29.29.29:53 -b -e
server 223.5.5.5:53 -b -e
server 223.6.6.6:53 -b -e
server [2400:3200:0000:0000:0000:0000:0000:0001]:53 -b -e
server [2400:3200:baba:0000:0000:0000:0000:0001]:53 -b -e
server [2402:4e00:0000:0000:0000:0000:0000:0000]:53 -b -e

server-tls dot.pub:853 -e -g chinadns
server-tls dns.alidns.com:853 -e -g chinadns

server-tls 1.0.0.1:853 -g otherdns
server-tls 1.1.1.1:853 -g otherdns
server-tls [2606:4700:4700:0000:0000:0000:0000:1001]:853 -g otherdns
server-tls [2606:4700:4700:0000:0000:0000:0000:1111]:853 -g otherdns

server-quic 94.140.14.140:853 -g otherdns
server-quic 94.140.14.141:853 -g otherdns
server-quic [2a10:50c0:0000:0000:0000:0000:0001:00ff]:853 -g otherdns
server-quic [2a10:50c0:0000:0000:0000:0000:0002:00ff]:853 -g otherdns

domain-set -name chinadns -type list -file /etc/smartdns/chinadns.list
domain-set -name otherdns -type list -file /etc/smartdns/otherdns.list
domain-rules /domain-set:chinadns/ -n chinadns
domain-rules /domain-set:otherdns/ -n otherdns
