on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 1 * *'
  push:
    branches: ["main"]

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: closehandle/smartdns:latest
